@endpoint = https://srqcwkm2nd.execute-api.ap-southeast-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: : application/json

{
  "location": "London",
  "name": "Best location"
}
###